require Rails.root.join("packs/shared/lib/elsewhere/values")
require Rails.root.join("packs/shared/lib/ai/task")
require Rails.root.join("packs/planning/lib/elsewhere/store")
require Rails.root.join("packs/supply/lib/supply")
require Rails.root.join("packs/planning/lib/planning")
require Rails.root.join("packs/foresight/lib/foresight")
